const upgrades = [
  { id:'butterGrip', name:'Butter Grip Handles', desc:'+1 toast/click. Adds a visible weight belt.', base:20, type:'toast', gear:'gear-belt', icon:'🏋️', buy:s=>{s.tap+=1;s.carbs+=2;} },
  { id:'crumbCore', name:'Crumb Core Protein', desc:'+0.8 toast/sec. Brock gains crumb delts.', base:55, type:'toast', gear:'gear-dumbbell', icon:'🏋️‍♂️', buy:s=>{s.tps+=0.8;s.protein+=4;} },
  { id:'sourdoughSpotter', name:'Sourdough Spotter', desc:'+2 toast/click. Adds gym shades.', base:140, type:'toast', gear:'gear-glasses', icon:'🕶️', buy:s=>{s.tap+=2;s.protein+=3;} },
  { id:'glutenGym', name:'Gluten Gym Membership', desc:'+4 toast/sec. Adds a gold chain.', base:420, type:'toast', gear:'gear-chain', icon:'⛓️', buy:s=>{s.tps+=4;s.protein+=7;} },
  { id:'extraToaster', name:'Extra Toaster Backpack', desc:'+12 toast/sec. A backpack toaster appears.', base:1100, type:'toast', gear:'gear-backpack', icon:'🎒', buy:s=>{s.tps+=12;s.carbs+=8;} },
  { id:'bagelBarbell', name:'Bagel Barbell Rack', desc:'+25 toast/sec. Circular carbs, linear progress.', base:2600, type:'toast', gear:'gear-hat', icon:'🤠', buy:s=>{s.tps+=25;s.protein+=10;} },
  { id:'grilledCheese', name:'Grilled Cheese Era', desc:'Unlocks grilled sandwich production and cheese drip.', base:9000, type:'toast', gear:'gear-cheese', icon:'🧀', buy:s=>{s.tps+=90;s.tap+=8;s.carbs+=12;} },
  { id:'kingdomStack', name:'Kingdom Stack', desc:'+500 toast/sec. Brock enters sandwich royalty.', base:50000, type:'toast', gear:'gear-crown', icon:'👑', buy:s=>{s.tps+=500;s.protein+=18;s.carbs+=18;} }
];

const spreads = [
  { id:'butter', name:'Butter', desc:'Classic. +15% click power.', base:120, apply:s=>{s.spreadTap+=0.15;s.carbs+=3;} },
  { id:'strawberry', name:'Strawberry Jam', desc:'+20% toast/sec.', base:500, apply:s=>{s.spreadTps+=0.20;s.carbs+=6;} },
  { id:'grape', name:'Grape Jelly', desc:'+10% click and +10% toast/sec.', base:1100, apply:s=>{s.spreadTap+=0.10;s.spreadTps+=0.10;s.carbs+=6;} },
  { id:'marmalade', name:'Orange Marmalade', desc:'+15% croutons on prestige.', base:2800, apply:s=>{s.croutonBonus+=0.15;s.carbs+=5;} },
  { id:'honey', name:'Honey', desc:'Butter boosts last 5 seconds longer.', base:6200, apply:s=>{s.boostBonusMs+=5000;s.carbs+=4;} },
  { id:'peanut', name:'Peanut Butter', desc:'+25% protein gains and swole growth.', base:15000, apply:s=>{s.proteinMult+=0.25;s.protein+=15;} },
  { id:'nutella', name:'Chocolate Hazelnut Spread', desc:'Chance for critical toasts on click.', base:40000, apply:s=>{s.critChance+=0.08;s.carbs+=10;} },
  { id:'cosmic', name:'Cosmic Jelly', desc:'+50% all production. Tastes like space.', base:150000, apply:s=>{s.spreadTap+=0.25;s.spreadTps+=0.25;s.croutonBonus+=0.25;s.carbs+=20;} }
];

const prestigeUpgrades = [
  { id:'strength', name:'Strength Training', desc:'+5% permanent protein effect.', base:1, apply:s=>{s.permProtein+=0.05;} },
  { id:'betterBread', name:'Better Bread', desc:'+5% permanent toast production.', base:2, apply:s=>{s.permToast+=0.05;} },
  { id:'butterDiscipline', name:'Butter Discipline', desc:'Butter boosts last 3 seconds longer forever.', base:3, apply:s=>{s.permBoostMs+=3000;} },
  { id:'texasGenes', name:'Texas Genetics', desc:'+10% permanent swole growth.', base:5, apply:s=>{s.permSwole+=0.10;} },
  { id:'doubleToasting', name:'Double Toasting', desc:'+5% crit chance forever.', base:8, apply:s=>{s.permCrit+=0.05;} },
  { id:'sandwichEngineering', name:'Sandwich Engineering', desc:'+15% grilled sandwich production.', base:13, apply:s=>{s.permSandwich+=0.15;} },
  { id:'familyRecipe', name:'Family Recipe', desc:'+10% spread power.', base:21, apply:s=>{s.permSpread+=0.10;} },
  { id:'loneStarLegacy', name:'Lone Star Legacy', desc:'Texas Toast events become stronger.', base:34, apply:s=>{s.permDad+=0.25;} }
];

const defaultState = {toast:0,lifetimeToast:0,totalLifetimeToast:0,tap:1,tps:0,last:Date.now(),boostUntil:0,croutons:0,carbs:50,protein:50,spreadTap:0,spreadTps:0,croutonBonus:0,boostBonusMs:0,proteinMult:0,critChance:0,permProtein:0,permToast:0,permBoostMs:0,permSwole:0,permCrit:0,permSandwich:0,permSpread:0,permDad:0,dadEventUntil:0,dadEventMult:1};
const BOOST_MULTIPLIER = 1.5, BOOST_DURATION_MS = 20000, BUTTER_VISIBLE_MS = 8500;
let state = load();
let butterTimer=null, dadTimer=null;
const $=id=>document.getElementById(id);
const els = ['toastCount','tps','tapPower','croutons','swoleRank','boostBanner','boostTime','ratioBanner','toastBtn','upgrades','spreads','prestige','floaties','butterLayer','visibleGear','yokeLabel','dadLine','storyText','prestigeBtn'].reduce((o,id)=>(o[id]=$(id),o),{});

function fmt(n){n=Number(n)||0;if(n<1000)return Math.floor(n).toLocaleString();const u=['K','M','B','T','Qa','Qi','Sx'];let i=-1;while(n>=1000&&i<u.length-1){n/=1000;i++;}return `${n.toFixed(n>=100?0:n>=10?1:2)}${u[i]}`;}
function ratio(){const c=Math.max(1,state.carbs),p=Math.max(1,state.protein*(1+state.proteinMult+state.permProtein));return {c,p,total:c+p,carbPct:c/(c+p)*100,proteinPct:p/(c+p)*100};}
function balanceMult(){const r=ratio();const dist=Math.abs(r.carbPct-50);if(dist<=5)return 3;if(dist<=10)return 2;if(dist<=20)return 1.25;if(r.carbPct>=80)return 0.85;if(r.proteinPct>=80)return 0.75;return 1;}
function boostActive(){return Date.now()<state.boostUntil;}
function dadActive(){return Date.now()<state.dadEventUntil;}
function tapMult(){return (1+state.spreadTap*(1+state.permSpread))*(1+state.permToast)*(boostActive()?BOOST_MULTIPLIER:1)*(dadActive()?state.dadEventMult:1)*balanceMult();}
function tpsMult(){let sandwich = upgrades.find(u=>u.id==='grilledCheese').count?1+state.permSandwich:1;return (1+state.spreadTps*(1+state.permSpread))*(1+state.permToast)*sandwich*(boostActive()?BOOST_MULTIPLIER:1)*(dadActive()?state.dadEventMult:1)*balanceMult();}
function activeTap(){return state.tap*tapMult();}
function activeTps(){return state.tps*tpsMult();}
function cost(u){return Math.floor(u.base*Math.pow(1.62,u.count||0));}
function prestigeCost(u){return Math.floor(u.base*Math.pow(2.25,u.count||0));}
function save(){state.last=Date.now();localStorage.setItem('yokedToastBrockV3',JSON.stringify({state,upgrades:upgrades.map(u=>[u.id,u.count||0]),spreads:spreads.map(u=>[u.id,u.count||0]),prestige:prestigeUpgrades.map(u=>[u.id,u.count||0])}));}
function load(){const raw=localStorage.getItem('yokedToastBrockV3')||localStorage.getItem('yokedToasterIdle');if(!raw)return structuredClone(defaultState);try{const data=JSON.parse(raw);(data.upgrades||[]).forEach(([id,c])=>{let u=upgrades.find(x=>x.id===id);if(u)u.count=c});(data.spreads||[]).forEach(([id,c])=>{let u=spreads.find(x=>x.id===id);if(u)u.count=c});(data.prestige||[]).forEach(([id,c])=>{let u=prestigeUpgrades.find(x=>x.id===id);if(u)u.count=c});let s={...defaultState,...(data.state||data)};let offline=Math.min(8*60*60,Math.max(0,(Date.now()-s.last)/1000));s.toast+=s.tps*offline;s.lifetimeToast=Math.max(s.lifetimeToast||0,s.toast);s.boostUntil=0;s.dadEventUntil=0;return s;}catch{return structuredClone(defaultState)}}
function buildList(container, items, mode){container.innerHTML='';items.forEach(u=>{u.count=u.count||0;const b=document.createElement('button');b.type='button';b.className='upgrade';b.dataset.id=u.id;b.innerHTML='<div><strong></strong><p></p></div><div class="cost"></div>';b.onclick=()=>mode==='croutons'?buyPrestige(u):buyToast(u);container.appendChild(b);});}
function buyToast(u){const c=cost(u);if(state.toast<c)return;state.toast-=c;u.count++;u.buy?u.buy(state):u.apply(state);popFloating(`-${fmt(c)} toast`,innerWidth-230,180);render();save();}
function buyPrestige(u){const c=prestigeCost(u);if(state.croutons<c)return;state.croutons-=c;u.count++;u.apply(state);popFloating(`-${fmt(c)} croutons`,innerWidth-230,180);render();save();}
function addToast(amount){state.toast+=amount;state.lifetimeToast+=amount;state.totalLifetimeToast+=amount;}
function makeToast(amount,x,y){let crit=Math.random()<state.critChance+state.permCrit;let final=crit?amount*5:amount;addToast(final);launchToast();popFloating(`${crit?'CRIT ':''}+${fmt(final)} 🍞`,x,y);render();}
function yokeTier(){let total=state.lifetimeToast;let bonus=1+state.permSwole+state.protein/300; if(total*bonus>=1000000)return 5;if(total*bonus>=150000)return 4;if(total*bonus>=40000)return 3;if(total*bonus>=8000)return 2;if(total*bonus>=900)return 1;return 0;}
function rank(){return ['Toast','Swole Toast','Sandwich Lord','Bread Titan','Carb Colossus','King of Toast'][yokeTier()]||'Toast Messiah';}
function stageName(){let t=state.lifetimeToast;if(t>250000)return 'Kingdom Stack';if(t>80000)return 'Mega Melt';if(t>25000)return 'Panini';if(t>9000)return 'Grilled Cheese';if(t>3000)return 'Sandwich';if(t>900)return 'Buttered Toast';return 'Toast';}
function renderGear(){const bought=upgrades.filter(u=>(u.count||0)>0).slice(0,8);els.visibleGear.innerHTML=bought.map(u=>`<span class="${u.gear}">${u.icon}</span>`).join('');}
function render(){const now=Date.now(),rem=Math.max(0,Math.ceil((state.boostUntil-now)/1000));els.toastCount.textContent=fmt(state.toast);els.tps.textContent=fmt(activeTps());els.tapPower.textContent=fmt(activeTap());els.croutons.textContent=fmt(state.croutons);els.swoleRank.textContent=rank();els.boostBanner.classList.toggle('hidden',rem<=0);els.boostTime.textContent=`${rem}s`;const r=ratio();let mood=Math.abs(r.carbPct-50)<=5?'MAXIMUM SWOLE':r.carbPct>=80?'Too carby: Brock skipped arm day':r.proteinPct>=80?'Too protein-heavy: Brock is posing':'Balanced gains';els.ratioBanner.textContent=`Protein ${Math.round(r.proteinPct)}% | Carbs ${Math.round(r.carbPct)}% — ${mood}`;els.toastBtn.className='toaster';let tier=yokeTier();if(tier>0)els.toastBtn.classList.add(`yoke-${tier}`);els.yokeLabel.textContent=`Stage: ${stageName()}. ${['Click Brock to make toast faster.','The Toastner genes are waking up.','Those crumb delts are coming in nicely.','Absolute sandwich unit.','Texas Toast is getting nervous.','Texas Toast reluctantly admits you are close.'][tier]}`;els.dadLine.textContent=dadActive()?'Looks like the Toastner genes finally kicked in.':'Son, every loaf starts with a single slice.';els.prestigeBtn.textContent=`Prestige for ${fmt(pendingCroutons())} croutons`;renderGear();updateButtons(upgrades,els.upgrades,'toast');updateButtons(spreads,els.spreads,'toast');updateButtons(prestigeUpgrades,els.prestige,'croutons');}
function updateButtons(items,container,currency){items.forEach(u=>{const btn=container.querySelector(`[data-id="${u.id}"]`);if(!btn)return;let c=currency==='croutons'?prestigeCost(u):cost(u);let wallet=currency==='croutons'?state.croutons:state.toast;btn.disabled=wallet<c;btn.querySelector('strong').innerHTML=`${u.name} <span>${currency==='croutons'?'Lv.':'Owned'} ${u.count||0}</span>`;btn.querySelector('p').textContent=u.desc;btn.querySelector('.cost').textContent=`${fmt(c)} ${currency==='croutons'?'🥖':'🍞'}`;});}
function pendingCroutons(){return Math.floor(Math.sqrt(state.lifetimeToast/10000)*(1+state.croutonBonus));}
function prestige(){let gain=pendingCroutons();if(gain<=0){alert('You need at least 10,000 lifetime toast before prestiging for croutons.');return;}if(!confirm(`Convert this run into ${gain} croutons and restart stronger?`))return;state.croutons+=gain;state.toast=0;state.lifetimeToast=0;state.tap=1;state.tps=0;state.boostUntil=0;state.carbs=50;state.protein=50;state.spreadTap=0;state.spreadTps=0;state.croutonBonus=0;state.boostBonusMs=0;state.proteinMult=0;state.critChance=0;upgrades.forEach(u=>u.count=0);spreads.forEach(u=>u.count=0);els.butterLayer.innerHTML='';showDadLine('Dad was right. It is time to start over stronger. A true Toastner is not afraid to get toasted twice.');render();save();}
function showDadLine(line){els.dadLine.textContent=line;popFloating('Texas Toast wisdom!',80,120);}
function launchToast(){const rect=els.toastBtn.getBoundingClientRect();const toast=document.createElement('div');toast.className='toast-piece';toast.textContent='🍞';toast.style.left=`${rect.left+rect.width/2}px`;toast.style.top=`${rect.top+22}px`;toast.style.setProperty('--drift',`${Math.round(Math.random()*90-45)}px`);toast.style.setProperty('--spin',`${Math.round(Math.random()*70-35)}deg`);document.body.appendChild(toast);setTimeout(()=>toast.remove(),950);}
function popFloating(text,x,y){const el=document.createElement('div');el.className='floaty';el.textContent=text;el.style.left=`${x}px`;el.style.top=`${y}px`;els.floaties.appendChild(el);setTimeout(()=>el.remove(),900);}
function randomButterDelay(){return 10000+Math.random()*10000;}function scheduleButter(){clearTimeout(butterTimer);butterTimer=setTimeout(spawnButter,randomButterDelay());}
function spawnButter(){if(document.querySelector('.butter-pad'))return scheduleButter();const pad=document.createElement('button');pad.type='button';pad.className='butter-pad';pad.textContent='🧈';const m=96;pad.style.left=`${m+Math.random()*Math.max(20,innerWidth-m*2)}px`;pad.style.top=`${m+Math.random()*Math.max(20,innerHeight-m*2)}px`;const expire=setTimeout(()=>{pad.remove();scheduleButter();},BUTTER_VISIBLE_MS);pad.onclick=e=>{clearTimeout(expire);state.boostUntil=Math.max(Date.now(),state.boostUntil)+BOOST_DURATION_MS+state.boostBonusMs+state.permBoostMs;popFloating('Butter pump! +50%',e.clientX,e.clientY);pad.remove();render();save();scheduleButter();};els.butterLayer.appendChild(pad);}
const events=[{title:'Fatherly Advice',text:'Texas Toast appears: “Son, every loaf starts with a single slice.”',choices:[['+25% production for 30 seconds',s=>{s.dadEventUntil=Date.now()+30000;s.dadEventMult=1.25+s.permDad;}]]},{title:'Tough Love',text:'Texas Toast squints. “You call those crumbs gains?”',choices:[['Train harder (+protein)',s=>{s.protein+=15*(1+s.permDad);}],['Eat more carbs (+toast production)',s=>{s.carbs+=15;s.tps+=5*(1+s.permDad);}]]},{title:'Family Cookout',text:'Texas Toast brought brisket, potato salad and questionable wisdom.',choices:[['Brisket (+protein)',s=>{s.protein+=20;}],['Potato salad (+carbs)',s=>{s.carbs+=20;}],['Both (+small bonus to each)',s=>{s.protein+=12;s.carbs+=12;}]]},{title:'Genetics Activated',text:'Texas Toast nods. “Looks like the Toastner genes finally kicked in.”',choices:[['Permanent +1% swole growth',s=>{s.permSwole+=0.01*(1+s.permDad);}]]}];
function scheduleDad(){clearTimeout(dadTimer);dadTimer=setTimeout(showEvent,45000+Math.random()*45000);}function showEvent(){const e=events[Math.floor(Math.random()*events.length)];$('eventTitle').textContent=e.title;$('eventText').textContent=e.text;const c=$('eventChoices');c.innerHTML='';e.choices.forEach(([label,fn])=>{const b=document.createElement('button');b.textContent=label;b.onclick=()=>{fn(state);$('eventModal').classList.add('hidden');render();save();scheduleDad();};c.appendChild(b);});$('eventModal').classList.remove('hidden');}

els.toastBtn.onclick=e=>makeToast(activeTap(),e.clientX,e.clientY);$('saveBtn').onclick=()=>{save();popFloating('Saved!',innerWidth-110,80);};els.prestigeBtn.onclick=prestige;$('closeEvent').onclick=()=>{$('eventModal').classList.add('hidden');scheduleDad();};document.querySelectorAll('.tab').forEach(tab=>tab.onclick=()=>{document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));tab.classList.add('active');['upgrades','spreads','prestige'].forEach(id=>$(id).classList.toggle('hidden',id!==tab.dataset.tab));});
buildList(els.upgrades,upgrades,'toast');buildList(els.spreads,spreads,'toast');buildList(els.prestige,prestigeUpgrades,'croutons');
let lastTick=performance.now();function loop(now){const d=(now-lastTick)/1000;lastTick=now;if(state.tps>0)addToast(activeTps()*d);render();requestAnimationFrame(loop);}render();scheduleButter();scheduleDad();setInterval(save,10000);requestAnimationFrame(loop);
